-- PokeWorld | 10_data/12_species.lua | Dữ liệu 32 loài Pokémon (base stats chuẩn Gen 1)
local PW = _G.PW or {}; _G.PW = PW

-- key = số dex quốc gia; gender_ratio = tỉ lệ đực (-1 = không giới tính)
PW.species = {
  [1] = {
    name_key = "sp.bulbasaur",
    types = {"grass", "poison"},
    base = {hp=45, atk=49, def=49, spa=65, spd=65, spe=45},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"overgrow"}, hidden_ability = "chlorophyll",
    egg_groups = {"monster", "grass"},
    height = 0.7, weight = 6.9,
    ev_yield = {spa=1},
    base_exp = 64,
    model_id = "mdl_bulbasaur", cry_id = "snd_cry_001",
  },
  [2] = {
    name_key = "sp.ivysaur",
    types = {"grass", "poison"},
    base = {hp=60, atk=62, def=63, spa=80, spd=80, spe=60},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"overgrow"}, hidden_ability = "chlorophyll",
    egg_groups = {"monster", "grass"},
    height = 1.0, weight = 13.0,
    ev_yield = {spa=1, spd=1},
    base_exp = 142,
    model_id = "mdl_ivysaur", cry_id = "snd_cry_002",
  },
  [3] = {
    name_key = "sp.venusaur",
    types = {"grass", "poison"},
    base = {hp=80, atk=82, def=83, spa=100, spd=100, spe=80},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"overgrow"}, hidden_ability = "chlorophyll",
    egg_groups = {"monster", "grass"},
    height = 2.0, weight = 100.0,
    ev_yield = {spa=2, spd=1},
    base_exp = 236,
    model_id = "mdl_venusaur", cry_id = "snd_cry_003",
  },
  [4] = {
    name_key = "sp.charmander",
    types = {"fire"},
    base = {hp=39, atk=52, def=43, spa=60, spd=50, spe=65},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"blaze"}, hidden_ability = "solar_power",
    egg_groups = {"monster", "dragon"},
    height = 0.6, weight = 8.5,
    ev_yield = {spe=1},
    base_exp = 62,
    model_id = "mdl_charmander", cry_id = "snd_cry_004",
  },
  [5] = {
    name_key = "sp.charmeleon",
    types = {"fire"},
    base = {hp=58, atk=64, def=58, spa=80, spd=65, spe=80},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"blaze"}, hidden_ability = "solar_power",
    egg_groups = {"monster", "dragon"},
    height = 1.1, weight = 19.0,
    ev_yield = {spa=1, spe=1},
    base_exp = 142,
    model_id = "mdl_charmeleon", cry_id = "snd_cry_005",
  },
  [6] = {
    name_key = "sp.charizard",
    types = {"fire", "flying"},
    base = {hp=78, atk=84, def=78, spa=109, spd=85, spe=100},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"blaze"}, hidden_ability = "solar_power",
    egg_groups = {"monster", "dragon"},
    height = 1.7, weight = 90.5,
    ev_yield = {spa=3},
    base_exp = 240,
    model_id = "mdl_charizard", cry_id = "snd_cry_006",
  },
  [7] = {
    name_key = "sp.squirtle",
    types = {"water"},
    base = {hp=44, atk=48, def=65, spa=50, spd=64, spe=43},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"torrent"}, hidden_ability = "rain_dish",
    egg_groups = {"monster", "water_1"},
    height = 0.5, weight = 9.0,
    ev_yield = {def=1},
    base_exp = 63,
    model_id = "mdl_squirtle", cry_id = "snd_cry_007",
  },
  [8] = {
    name_key = "sp.wartortle",
    types = {"water"},
    base = {hp=59, atk=63, def=80, spa=65, spd=80, spe=58},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"torrent"}, hidden_ability = "rain_dish",
    egg_groups = {"monster", "water_1"},
    height = 1.0, weight = 22.5,
    ev_yield = {def=1, spd=1},
    base_exp = 142,
    model_id = "mdl_wartortle", cry_id = "snd_cry_008",
  },
  [9] = {
    name_key = "sp.blastoise",
    types = {"water"},
    base = {hp=79, atk=83, def=100, spa=85, spd=105, spe=78},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.875,
    abilities = {"torrent"}, hidden_ability = "rain_dish",
    egg_groups = {"monster", "water_1"},
    height = 1.6, weight = 85.5,
    ev_yield = {spd=3},
    base_exp = 239,
    model_id = "mdl_blastoise", cry_id = "snd_cry_009",
  },
  [10] = {
    name_key = "sp.caterpie",
    types = {"bug"},
    base = {hp=45, atk=30, def=35, spa=20, spd=20, spe=45},
    catch_rate = 255,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"shield_dust"}, hidden_ability = "run_away",
    egg_groups = {"bug"},
    height = 0.3, weight = 2.9,
    ev_yield = {hp=1},
    base_exp = 39,
    model_id = "mdl_caterpie", cry_id = "snd_cry_010",
  },
  [11] = {
    name_key = "sp.metapod",
    types = {"bug"},
    base = {hp=50, atk=20, def=55, spa=25, spd=25, spe=30},
    catch_rate = 120,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"shed_skin"}, hidden_ability = nil,
    egg_groups = {"bug"},
    height = 0.7, weight = 9.9,
    ev_yield = {def=2},
    base_exp = 72,
    model_id = "mdl_metapod", cry_id = "snd_cry_011",
  },
  [12] = {
    name_key = "sp.butterfree",
    types = {"bug", "flying"},
    base = {hp=60, atk=45, def=50, spa=90, spd=80, spe=70},
    catch_rate = 45,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"compound_eyes"}, hidden_ability = "tinted_lens",
    egg_groups = {"bug"},
    height = 1.1, weight = 32.0,
    ev_yield = {spa=2, spd=1},
    base_exp = 178,
    model_id = "mdl_butterfree", cry_id = "snd_cry_012",
  },
  [16] = {
    name_key = "sp.pidgey",
    types = {"normal", "flying"},
    base = {hp=40, atk=45, def=40, spa=35, spd=35, spe=56},
    catch_rate = 255,
    exp_curve = "medium_slow",
    gender_ratio = 0.5,
    abilities = {"keen_eye", "tangled_feet"}, hidden_ability = "big_pecks",
    egg_groups = {"flying"},
    height = 0.3, weight = 1.8,
    ev_yield = {spe=1},
    base_exp = 50,
    model_id = "mdl_pidgey", cry_id = "snd_cry_016",
  },
  [17] = {
    name_key = "sp.pidgeotto",
    types = {"normal", "flying"},
    base = {hp=63, atk=60, def=55, spa=50, spd=50, spe=71},
    catch_rate = 120,
    exp_curve = "medium_slow",
    gender_ratio = 0.5,
    abilities = {"keen_eye", "tangled_feet"}, hidden_ability = "big_pecks",
    egg_groups = {"flying"},
    height = 1.1, weight = 30.0,
    ev_yield = {spe=2},
    base_exp = 122,
    model_id = "mdl_pidgeotto", cry_id = "snd_cry_017",
  },
  [18] = {
    name_key = "sp.pidgeot",
    types = {"normal", "flying"},
    base = {hp=83, atk=80, def=75, spa=70, spd=70, spe=101},
    catch_rate = 45,
    exp_curve = "medium_slow",
    gender_ratio = 0.5,
    abilities = {"keen_eye", "tangled_feet"}, hidden_ability = "big_pecks",
    egg_groups = {"flying"},
    height = 1.5, weight = 39.5,
    ev_yield = {spe=3},
    base_exp = 216,
    model_id = "mdl_pidgeot", cry_id = "snd_cry_018",
  },
  [19] = {
    name_key = "sp.rattata",
    types = {"normal"},
    base = {hp=30, atk=56, def=35, spa=25, spd=35, spe=72},
    catch_rate = 255,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"run_away", "guts"}, hidden_ability = "hustle",
    egg_groups = {"field"},
    height = 0.3, weight = 3.5,
    ev_yield = {spe=1},
    base_exp = 51,
    model_id = "mdl_rattata", cry_id = "snd_cry_019",
  },
  [20] = {
    name_key = "sp.raticate",
    types = {"normal"},
    base = {hp=55, atk=81, def=60, spa=50, spd=70, spe=97},
    catch_rate = 127,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"run_away", "guts"}, hidden_ability = "hustle",
    egg_groups = {"field"},
    height = 0.7, weight = 18.5,
    ev_yield = {spe=2},
    base_exp = 145,
    model_id = "mdl_raticate", cry_id = "snd_cry_020",
  },
  [25] = {
    name_key = "sp.pikachu",
    types = {"electric"},
    base = {hp=35, atk=55, def=40, spa=50, spd=50, spe=90},
    catch_rate = 190,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"static"}, hidden_ability = "lightning_rod",
    egg_groups = {"field", "fairy"},
    height = 0.4, weight = 6.0,
    ev_yield = {spe=2},
    base_exp = 112,
    model_id = "mdl_pikachu", cry_id = "snd_cry_025",
  },
  [26] = {
    name_key = "sp.raichu",
    types = {"electric"},
    base = {hp=60, atk=90, def=55, spa=90, spd=80, spe=110},
    catch_rate = 75,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"static"}, hidden_ability = "lightning_rod",
    egg_groups = {"field", "fairy"},
    height = 0.8, weight = 30.0,
    ev_yield = {spe=3},
    base_exp = 218,
    model_id = "mdl_raichu", cry_id = "snd_cry_026",
  },
  [41] = {
    name_key = "sp.zubat",
    types = {"poison", "flying"},
    base = {hp=40, atk=45, def=35, spa=30, spd=40, spe=55},
    catch_rate = 255,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"inner_focus"}, hidden_ability = "infiltrator",
    egg_groups = {"flying"},
    height = 0.8, weight = 7.5,
    ev_yield = {spe=1},
    base_exp = 49,
    model_id = "mdl_zubat", cry_id = "snd_cry_041",
  },
  [42] = {
    name_key = "sp.golbat",
    types = {"poison", "flying"},
    base = {hp=75, atk=80, def=70, spa=65, spd=75, spe=90},
    catch_rate = 90,
    exp_curve = "medium_fast",
    gender_ratio = 0.5,
    abilities = {"inner_focus"}, hidden_ability = "infiltrator",
    egg_groups = {"flying"},
    height = 1.6, weight = 55.0,
    ev_yield = {spe=2},
    base_exp = 159,
    model_id = "mdl_golbat", cry_id = "snd_cry_042",
  },
  [43] = {
    name_key = "sp.oddish",
    types = {"grass", "poison"},
    base = {hp=45, atk=50, def=55, spa=75, spd=65, spe=30},
    catch_rate = 255,
    exp_curve = "medium_slow",
    gender_ratio = 0.5,
    abilities = {"chlorophyll"}, hidden_ability = "run_away",
    egg_groups = {"grass"},
    height = 0.5, weight = 5.4,
    ev_yield = {spa=1},
    base_exp = 64,
    model_id = "mdl_oddish", cry_id = "snd_cry_043",
  },
  [44] = {
    name_key = "sp.gloom",
    types = {"grass", "poison"},
    base = {hp=60, atk=65, def=70, spa=85, spd=75, spe=40},
    catch_rate = 120,
    exp_curve = "medium_slow",
    gender_ratio = 0.5,
    abilities = {"chlorophyll"}, hidden_ability = "stench",
    egg_groups = {"grass"},
    height = 0.8, weight = 8.6,
    ev_yield = {spa=2},
    base_exp = 138,
    model_id = "mdl_gloom", cry_id = "snd_cry_044",
  },
  [66] = {
    name_key = "sp.machop",
    types = {"fighting"},
    base = {hp=70, atk=80, def=50, spa=35, spd=35, spe=35},
    catch_rate = 180,
    exp_curve = "medium_slow",
    gender_ratio = 0.75,
    abilities = {"guts", "no_guard"}, hidden_ability = "steadfast",
    egg_groups = {"human_like"},
    height = 0.8, weight = 19.5,
    ev_yield = {atk=1},
    base_exp = 61,
    model_id = "mdl_machop", cry_id = "snd_cry_066",
  },
  [67] = {
    name_key = "sp.machoke",
    types = {"fighting"},
    base = {hp=80, atk=100, def=70, spa=50, spd=60, spe=45},
    catch_rate = 90,
    exp_curve = "medium_slow",
    gender_ratio = 0.75,
    abilities = {"guts", "no_guard"}, hidden_ability = "steadfast",
    egg_groups = {"human_like"},
    height = 1.5, weight = 70.5,
    ev_yield = {atk=2},
    base_exp = 142,
    model_id = "mdl_machoke", cry_id = "snd_cry_067",
  },
  [74] = {
    name_key = "sp.geodude",
    types = {"rock", "ground"},
    base = {hp=40, atk=80, def=100, spa=30, spd=30, spe=20},
    catch_rate = 255,
    exp_curve = "medium_slow",
    gender_ratio = 0.5,
    abilities = {"rock_head", "sturdy"}, hidden_ability = "sand_veil",
    egg_groups = {"mineral"},
    height = 0.4, weight = 20.0,
    ev_yield = {def=1},
    base_exp = 60,
    model_id = "mdl_geodude", cry_id = "snd_cry_074",
  },
  [75] = {
    name_key = "sp.graveler",
    types = {"rock", "ground"},
    base = {hp=55, atk=95, def=115, spa=45, spd=45, spe=35},
    catch_rate = 120,
    exp_curve = "medium_slow",
    gender_ratio = 0.5,
    abilities = {"rock_head", "sturdy"}, hidden_ability = "sand_veil",
    egg_groups = {"mineral"},
    height = 1.0, weight = 105.0,
    ev_yield = {def=2},
    base_exp = 137,
    model_id = "mdl_graveler", cry_id = "snd_cry_075",
  },
  [129] = {
    name_key = "sp.magikarp",
    types = {"water"},
    base = {hp=20, atk=10, def=55, spa=15, spd=20, spe=80},
    catch_rate = 255,
    exp_curve = "slow",
    gender_ratio = 0.5,
    abilities = {"swift_swim"}, hidden_ability = "rattled",
    egg_groups = {"water_2", "dragon"},
    height = 0.9, weight = 10.0,
    ev_yield = {spe=1},
    base_exp = 40,
    model_id = "mdl_magikarp", cry_id = "snd_cry_129",
  },
  [130] = {
    name_key = "sp.gyarados",
    types = {"water", "flying"},
    base = {hp=95, atk=125, def=79, spa=60, spd=100, spe=81},
    catch_rate = 45,
    exp_curve = "slow",
    gender_ratio = 0.5,
    abilities = {"intimidate"}, hidden_ability = "moxie",
    egg_groups = {"water_2", "dragon"},
    height = 6.5, weight = 235.0,
    ev_yield = {atk=2},
    base_exp = 189,
    model_id = "mdl_gyarados", cry_id = "snd_cry_130",
  },
  [133] = {
    name_key = "sp.eevee",
    types = {"normal"},
    base = {hp=55, atk=55, def=50, spa=45, spd=65, spe=55},
    catch_rate = 45,
    exp_curve = "medium_fast",
    gender_ratio = 0.875,
    abilities = {"run_away", "adaptability"}, hidden_ability = "anticipation",
    egg_groups = {"field"},
    height = 0.3, weight = 6.5,
    ev_yield = {spd=1},
    base_exp = 65,
    model_id = "mdl_eevee", cry_id = "snd_cry_133",
  },
  [143] = {
    name_key = "sp.snorlax",
    types = {"normal"},
    base = {hp=160, atk=110, def=65, spa=65, spd=110, spe=30},
    catch_rate = 25,
    exp_curve = "slow",
    gender_ratio = 0.875,
    abilities = {"immunity", "thick_fat"}, hidden_ability = "gluttony",
    egg_groups = {"monster"},
    height = 2.1, weight = 460.0,
    ev_yield = {hp=2},
    base_exp = 189,
    model_id = "mdl_snorlax", cry_id = "snd_cry_143",
  },
  [147] = {
    name_key = "sp.dratini",
    types = {"dragon"},
    base = {hp=41, atk=64, def=45, spa=50, spd=50, spe=50},
    catch_rate = 45,
    exp_curve = "slow",
    gender_ratio = 0.5,
    abilities = {"shed_skin"}, hidden_ability = "marvel_scale",
    egg_groups = {"water_1", "dragon"},
    height = 1.8, weight = 3.3,
    ev_yield = {atk=1},
    base_exp = 60,
    model_id = "mdl_dratini", cry_id = "snd_cry_147",
  },
}
